# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kanban < Formula
  desc "Git-native kanban task management CLI — board state driven by commits and CI"
  homepage "https://github.com/jmsargent/Kanban"
  version "0.67.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jmsargent/Kanban/releases/download/v0.67.1/kanban_0.67.1_darwin_amd64.tar.gz"
      sha256 "b81ca5499ece02256eb770ec9457d538b0b75025c7c2e44fe4993f2e204e3d14"

      define_method(:install) do
        bin.install "kanban"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jmsargent/Kanban/releases/download/v0.67.1/kanban_0.67.1_darwin_arm64.tar.gz"
      sha256 "4cf24f2152a2e05890c01b21a21d9f525a2fd460a71f319e2a0b6c41f704ddfe"

      define_method(:install) do
        bin.install "kanban"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmsargent/Kanban/releases/download/v0.67.1/kanban_0.67.1_linux_amd64.tar.gz"
      sha256 "b13446382670834fe70ed6737870202ab53179934edc19be9008c13e2807f319"
      define_method(:install) do
        bin.install "kanban"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmsargent/Kanban/releases/download/v0.67.1/kanban_0.67.1_linux_arm64.tar.gz"
      sha256 "8e9de6239ba96673d17e1aac05ccb8d44c0a7695eca2d79bc6497b4d1addf989"
      define_method(:install) do
        bin.install "kanban"
      end
    end
  end

  test do
    system "#{bin}/kanban", "--version"
  end
end
