# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kanban < Formula
  desc "Git-native kanban task management CLI — board state driven by commits and CI"
  homepage "https://github.com/jmsargent/Kanban"
  version "0.57.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jmsargent/Kanban/releases/download/v0.57.0/kanban_0.57.0_darwin_amd64.tar.gz"
      sha256 "379f595a96fb7ffe02b7dff690766f6a0643989d278f7b14b01192b3a2f749c5"

      define_method(:install) do
        bin.install "kanban"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jmsargent/Kanban/releases/download/v0.57.0/kanban_0.57.0_darwin_arm64.tar.gz"
      sha256 "6c197639e22680c7b58965bba975eaf74f7dbedb33503d14649a4c699aea73bd"

      define_method(:install) do
        bin.install "kanban"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmsargent/Kanban/releases/download/v0.57.0/kanban_0.57.0_linux_amd64.tar.gz"
      sha256 "5d8d43cc6978dde30e3a72377587d0cfcdb9d3a826f32896dd798179f4cbc243"
      define_method(:install) do
        bin.install "kanban"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmsargent/Kanban/releases/download/v0.57.0/kanban_0.57.0_linux_arm64.tar.gz"
      sha256 "200d68aa179c44b8ee77261daea18fb676eb5ef15819acd2c61f9d65fa818d5a"
      define_method(:install) do
        bin.install "kanban"
      end
    end
  end

  test do
    system "#{bin}/kanban", "--version"
  end
end
